### ISSUE TITLE
CloudStackClusterTemplate API and CRD request to use with clusterclass implementation

### ISSUE THREAD

**Issue by ozhankaraman** [kubernetes-sigs/cluster-api-provider-cloudstack#287]
/kind feature

**Describe the solution you'd like**
I like to use Cluster-api ClusterClass solution to manage our cluster topology easily with Cluster-api CloudStack deployments. I checked default configuration detailed here https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/write-clusterclass.html#basic-clusterclass but I noticed that we don't have crd, api definition for CloudStackClusterTemplate, when I deploy sample clusterclass I got the error below

error: resource mapping not found for name: "capc-sharedkv" namespace: "" from "capc-sharedkv-cc.yaml": no matches for kind "CloudStackClusterTemplate" in version "infrastructure.cluster.x-k8s.io/v1beta2"

Do we plan to include this on upcoming release?

**Anything else you would like to add:**
My clusterclass definition is below.
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: capc-sharedkv-cc-1.0
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: capc-sharedkv-cp # Done
      namespace: default
    machineInfrastructure:
      ref:
        kind: CloudStackMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        name: capc-sharedkv-cp-v1-26-6 # Done
        namespace: default
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: CloudStackClusterTemplate
      name: capc-sharedkv # TODO
      namespace: default
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: capc-sharedkv-md-v1-26-6 # Done
            namespace: default
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: CloudStackMachineTemplate
            name: capc-sharedkv-md-v1-26-6 # Done
            namespace: default
```

**Environment:**

- Cluster-api-provider-cloudstack version:  v0.4.8
- Kubernetes version: (use `kubectl version`): 1.26.6
- OS (e.g. from `/etc/os-release`): debian11
