### ISSUE TITLE
DiskOffering in CloudStackMachine CRD should be a pointer to CloudStackResourceDiskOffering

### ISSUE THREAD

**Issue by hrak** [kubernetes-sigs/cluster-api-provider-cloudstack#326]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

`DiskOffering` is an optional field in the `CloudStackMachine` CRD. It is currently defined as:

```
	// CloudStack disk offering to use.
	// +optional
	DiskOffering CloudStackResourceDiskOffering `json:"diskOffering,omitempty"`
```

This can lead to unnecessary reconciliations or even unintended behavior when this field is omitted from a yaml definition, because the entire structure will be included in the final object definition with its default values:

```yaml
spec:
  diskOffering:
    customSizeInGB: 0
    device: ""
    filesystem: ""
    label: ""
    mountPath: ""
  failureDomainName: failure-domain-1
  offering:
    name: Medium Instance (8 GB / 4 CPU)
  sshKey: h.rakers-ed25519
```

`DiskOffering` should be changed to `*CloudStackResourceDiskOffering` to comply with the [Kubernetes API conventions](https://github.com/zecke/Kubernetes/blob/master/docs/devel/api-conventions.md#optional-vs-required).
